### ISSUE TITLE
Using gulp-newer to compile a LESS file with @import

### ISSUE THREAD

**Issue by danielbayerlein** [tschaub/gulp-newer#16]
gulp-newer ignored `@import` in LESS files.

---

**Example**

*a.less* imported *b.less*
```less
@import "b.less";
```

If I change *b.less*,  gulp-newer does not recompile *a.less*.

---

**Source**

```less
gulp.task('less', function() {
  return gulp.src('lib/a.less')
    .pipe(newer('dist/a.css'))
    .pipe(less())
    .pipe(gulp.dest('dist'));
});
```

**Comment by danielbayerlein** [comment]
@tschaub Do you have any idea how to solve the problem?

**Comment by tschaub** [comment]
Since the `newer` plugin is not specific to LESS, it doesn't know anything about `@import`.  One general way to handle this problem would be to configure `newer` with a function that resolves dependencies for incoming source files.  Unfortunately, to create this function correctly involves reproducing a lot of work done elsewhere (e.g. in the `less` plugin).
