### ISSUE TITLE
Checking for changes accross teams

### ISSUE THREAD

**Issue by RehanSaeed** [tschaub/gulp-newer#36]
I want to use gulp-imagemin which is a very slow and processor intensive task and I am working in a team environment using Git. How can I make sure that an image is only ever processed once in my entire team? Where does gulp-changed-in-place save it's change log? Can it be checked-in to Git?

**Comment by tschaub** [comment]
The `gulp-newer` plugin works by comparing modification times of source files to modification times of destination files.  If you have both source and destination files checked into git, git should only update modification times [when a file is changed](https://git.wiki.kernel.org/index.php/GitFaq#Why_isn.27t_Git_preserving_modification_time_on_files.3F) - so things should just work.  But I'm guessing that since you opened this issue, you are not getting the behavior you expect.

**Comment by RehanSaeed** [comment]
I'm trying to evaluate a few NPM plugin that all claim to do the same thing. In my case my source and destination files are both the same file, just a minified version. So I guess, gulp-newer is not the right tool in this case?

**Comment by tschaub** [comment]
If you are overwriting your source files with your destination content, then `gulp-newer` is not going to be of use.

**Comment by RehanSaeed** [comment]
Great, thanks!
